name: Call Deploy Action

on:
  push:
    branches:
      - main
    paths:
      - "Backend/**"
      - ".github/**"

jobs:
  Deploy:
    strategy:
      matrix:
        lambda:
          [
            LOR__check-match,
            LOR__check_new_player,
            LOR__save-match-data,
            LOR__analyze-match-data,
            LOR__refresh-leaderboards,

            LOR__get-all-champion-card,
            LOR__get-all-meta-deck,
            LOR__get-all-version-data,
            LOR__get-comparison-meta-deck-data-by-cards,
            LOR__get-lastest-version-data,
            LOR__get-meta-deck-detail,
            LOR__get-version-data,
            LOR__get-all-comparison-meta-deck,
          ]
        include:
          - lambda: LOR__check-match
            path: ./Backend/cron/check_match
          - lambda: LOR__check_new_player
            path: ./Backend/cron/check_new_player
          - lambda: LOR__save-match-data
            path: ./Backend/cron/save_match_data
          - lambda: LOR__analyze-match-data
            path: ./Backend/cron/analyze_match_data
          - lambda: LOR__refresh-leaderboards
            path: ./Backend/cron/refresh_leaderboards
          - lambda: LOR__get-all-champion-card
            path: ./Backend/api/v1/get_all_champion_card
          - lambda: LOR__get-all-meta-deck
            path: ./Backend/api/v1/get_all_meta_deck
          - lambda: LOR__get-all-version-data
            path: ./Backend/api/v1/get_all_version_data
          - lambda: LOR__get-comparison-meta-deck-data-by-cards
            path: ./Backend/api/v1/get_comparison_meta_deck_data_by_cards
          - lambda: LOR__get-lastest-version-data
            path: ./Backend/api/v1/get_lastest_version_data
          - lambda: LOR__get-meta-deck-detail
            path: ./Backend/api/v1/get_meta_deck_detail
          - lambda: LOR__get-version-data
            path: ./Backend/api/v1/get_version_data
          - lambda: LOR__get-all-comparison-meta-deck
            path: ./Backend/api/v1/get_all_comparison_meta_deck_data

    uses: junah201/Runeterras.com/.github/workflows/deploy.yml@main
    with:
      file_path: ${{ matrix.path }}
      lambda_name: ${{ matrix.lambda }}
    secrets: inherit
