name: AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: x64
          cache: "pip"

      - name: Install Python module
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          pip install -r ./Backend/requirements.txt

      - name: Python files to Zip file
        run: |
          (cd ./venv/lib/python3.9/site-packages; zip -r9 ../../../../Build.zip . )
          (cd ./Backend; zip ../Build.zip -u -r check_match.py database.py models.py refresh_leaderboards.py save_match_data.py check_new_player.py analyze_match_data.py;)
          (cd ./Backend/api/v1; zip ../../../Build.zip -u -r get_lastest_version_data.py get_all_version_data.py get_all_meta_deck.py get_meta_deck_detail.py get_version_data.py get_all_champion_card.py get_comparison_meta_deck_data_by_cards.py;)

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: lor-build
          path: Build.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda Build.zip
        uses: actions/download-artifact@v2
        with:
          name: lor-build

      - name: Upload to S3
        run: aws s3 cp Build.zip s3://lor-build/Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__check-match
        run: aws lambda update-function-code --function-name LOR__check-match --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__save-match-data
        run: aws lambda update-function-code --function-name LOR__save-match-data --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__refresh-leaderboards
        run: aws lambda update-function-code --function-name LOR__refresh-leaderboards --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__check_new_player
        run: aws lambda update-function-code --function-name LOR__check_new_player --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__analyze-match-data
        run: aws lambda update-function-code --function-name LOR__analyze-match-data --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__get-lastest-version-data
        run: aws lambda update-function-code --function-name LOR__get-lastest-version-data --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__get-all-version-data
        run: aws lambda update-function-code --function-name LOR__get-all-version-data --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__get-all-meta-deck
        run: aws lambda update-function-code --function-name LOR__get-all-meta-deck --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__get-meta-deck-detail
        run: aws lambda update-function-code --function-name LOR__get-meta-deck-detail --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__get-version-data
        run: aws lambda update-function-code --function-name LOR__get-version-data --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__get-all-champion-card
        run: aws lambda update-function-code --function-name LOR__get-all-champion-card --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy LOR__get-comparison-meta-deck-data-by-cards
        run: aws lambda update-function-code --function-name LOR__get-comparison-meta-deck-data-by-cards --s3-bucket lor-build --s3-key Build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
